package edu.hm.ccwi.semantic.jena.vocabulary;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from twtr.ttl
 *
 * @author Auto-generated by schemagen on 22 Apr 2017 15:04
 */
public class TWTR {
    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://example.org/";
    /**
     * <p>The RDF model that holds the vocabulary terms</p>
     */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);
    /**
     * <p>Amount of users who have subscribed to a Twitter Account.</p>
     */
    public static final Property followerCount = M_MODEL.createProperty("http://example.org/followerCount");
    /**
     * <p>A Tweet might mention a subject.</p>
     */
    public static final Property mentions = M_MODEL.createProperty("http://example.org/mentions");
    /**
     * <p>A Tweet ID.</p>
     */
    public static final Property tweetID = M_MODEL.createProperty("http://example.org/tweetID");
    /**
     * <p>A status message within Twitter.</p>
     */
    public static final Property tweetText = M_MODEL.createProperty("http://example.org/tweetText");
    /**
     * <p>A Tweet gets tweeted from a TwitterAccount.</p>
     */
    public static final Property tweeted = M_MODEL.createProperty("http://example.org/tweeted");
    /**
     * <p>A short personal description of a Twitter Account.</p>
     */
    public static final Property userDescription = M_MODEL.createProperty("http://example.org/userDescription");
    /**
     * <p>A Twitter Account ID.</p>
     */
    public static final Property userID = M_MODEL.createProperty("http://example.org/userID");
    /**
     * <p>A short informal nickname characterising a Twitter Account.</p>
     */
    public static final Property userName = M_MODEL.createProperty("http://example.org/userName");
    /**
     * <p>A tweet is a text message limited to 140 characters in length, that is broadcast
     * and readable by anyone who accesses Twitter.</p>
     */
    public static final Resource Tweet = M_MODEL.createResource("http://example.org/Tweet");
    /**
     * <p>The relation between a phrase and a verb in a tweet, in which the relation
     * is central to the verb.</p>
     */
    public static final Resource TweetObject = M_MODEL.createResource("http://example.org/TweetObject");
    /**
     * <p>The relation between a phrase and a verb in a tweet, that represents the person
     * or thing that performs the action or about which something is stated.</p>
     */
    public static final Resource TweetSubject = M_MODEL.createResource("http://example.org/TweetSubject");
    /**
     * <p>An account on the social networking site Twitter</p>
     */
    public static final Resource TwitterAccount = M_MODEL.createResource("http://example.org/TwitterAccount");

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @return namespace as String
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

}
