package edu.hm.ccwi.semantic.rdf.vocab;/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/ralph/Documents/Entwicklung/Java/twtr/src/main/resources/vocab/twtr.ttl 
 * @author Auto-generated by schemagen on 07 Jun 2017 15:36 
 */
public class TWTR {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://example.org/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>A Tweet contains Part-of-Speech-Information.</p> */
    public static final Property contains = M_MODEL.createProperty( "http://example.org/contains" );
    
    /** <p>The name of the Entity.</p> */
    public static final Property entityName = M_MODEL.createProperty( "http://example.org/entityName" );
    
    /** <p>Amount of users who have subscribed to a Twitter Account.</p> */
    public static final Property followerCount = M_MODEL.createProperty( "http://example.org/followerCount" );
    
    /** <p>A Tweet has a keyword.</p> */
    public static final Property hasKeyword = M_MODEL.createProperty( "http://example.org/hasKeyword" );
    
    /** <p>The keyword itself.</p> */
    public static final Property keywordText = M_MODEL.createProperty( "http://example.org/keywordText" );
    
    /** <p>A Tweet ID.</p> */
    public static final Property tweetID = M_MODEL.createProperty( "http://example.org/tweetID" );
    
    /** <p>A status message within Twitter.</p> */
    public static final Property tweetText = M_MODEL.createProperty( "http://example.org/tweetText" );
    
    /** <p>A Tweet gets tweeted from a TwitterAccount.</p> */
    public static final Property tweeted = M_MODEL.createProperty( "http://example.org/tweeted" );
    
    /** <p>A short personal description of a Twitter Account.</p> */
    public static final Property userDescription = M_MODEL.createProperty( "http://example.org/userDescription" );
    
    /** <p>A Twitter Account ID.</p> */
    public static final Property userID = M_MODEL.createProperty( "http://example.org/userID" );
    
    /** <p>A short informal nickname characterising a Twitter Account.</p> */
    public static final Property userName = M_MODEL.createProperty( "http://example.org/userName" );
    
    /** <p>The word of the POS.</p> */
    public static final Property word = M_MODEL.createProperty( "http://example.org/word" );
    
    /** <p>An Adjective</p> */
    public static final Resource Adjective = M_MODEL.createResource( "http://example.org/Adjective" );
    
    /** <p>A Common Noun</p> */
    public static final Resource CommonNoun = M_MODEL.createResource( "http://example.org/CommonNoun" );
    
    /** <p>A Entity.</p> */
    public static final Resource Entity = M_MODEL.createResource( "http://example.org/Entity" );
    
    /** <p>Keyword of the Tweet.</p> */
    public static final Resource Keyword = M_MODEL.createResource( "http://example.org/Keyword" );
    
    /** <p>The relation between a phrase and a verb in a tweet, in which the relation 
     *  is central to the verb.</p>
     */
    public static final Resource Object = M_MODEL.createResource( "http://example.org/Object" );
    
    /** <p>POS.</p> */
    public static final Resource POS = M_MODEL.createResource( "http://example.org/POS" );
    
    /** <p>A Proper Noun</p> */
    public static final Resource ProperNoun = M_MODEL.createResource( "http://example.org/ProperNoun" );
    
    /** <p>The relation between a phrase and a verb in a tweet, that represents the person 
     *  or thing that performs the action or about which something is stated.</p>
     */
    public static final Resource Subject = M_MODEL.createResource( "http://example.org/Subject" );
    
    /** <p>SVO-Triplet.</p> */
    public static final Resource Triplet = M_MODEL.createResource( "http://example.org/Triplet" );
    
    /** <p>A tweet is a text message limited to 140 characters in length, that is broadcast 
     *  and readable by anyone who accesses Twitter.</p>
     */
    public static final Resource Tweet = M_MODEL.createResource( "http://example.org/Tweet" );
    
    /** <p>An account on the social networking site Twitter</p> */
    public static final Resource TwitterAccount = M_MODEL.createResource( "http://example.org/TwitterAccount" );
    
    /** <p>A verb signals an action, an occurrence, or a state of being.</p> */
    public static final Resource Verb = M_MODEL.createResource( "http://example.org/Verb" );
    
}
