package edu.hm.ccwi.semantic.rdf.vocab;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from /Users/ralph/Documents/Entwicklung/Java/twtr/src/main/resources/vocab/twtr.ttl
 *
 * @author Auto -generated by schemagen on 25 Apr 2017 13:03
 */
public class TWTR {
    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://example.org/";
    /**
     * <p>The RDF model that holds the vocabulary terms</p>
     */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = M_MODEL.createResource(NS);
    /**
     * <p>A Tweets has part of speech.</p>
     */
    public static final Property contains = M_MODEL.createProperty("http://example.org/contains");
    /**
     * <p>Amount of users who have subscribed to a Twitter Account.</p>
     */
    public static final Property followerCount = M_MODEL.createProperty("http://example.org/followerCount");
    /**
     * <p>A Twitter Account and a proper noun can be a Entity.</p>
     */
    public static final Property isA = M_MODEL.createProperty("http://example.org/isA");
    /**
     * <p>A Tweet might mention a SVO Triple.</p>
     */
    public static final Property mentions = M_MODEL.createProperty("http://example.org/mentions");
    /**
     * <p>Text of a Subject, Verb or Object.</p>
     */
    public static final Property text = M_MODEL.createProperty("http://example.org/text");
    /**
     * <p>A Tweet ID.</p>
     */
    public static final Property tweetID = M_MODEL.createProperty("http://example.org/tweetID");
    /**
     * <p>A status message within Twitter.</p>
     */
    public static final Property tweetText = M_MODEL.createProperty("http://example.org/tweetText");
    /**
     * <p>A Tweet gets tweeted from a TwitterAccount.</p>
     */
    public static final Property tweeted = M_MODEL.createProperty("http://example.org/tweeted");
    /**
     * <p>A short personal description of a Twitter Account.</p>
     */
    public static final Property userDescription = M_MODEL.createProperty("http://example.org/userDescription");
    /**
     * <p>A Twitter Account ID.</p>
     */
    public static final Property userID = M_MODEL.createProperty("http://example.org/userID");
    /**
     * <p>A short informal nickname characterising a Twitter Account.</p>
     */
    public static final Property userName = M_MODEL.createProperty("http://example.org/userName");
    /**
     * <p>The word of the POS.</p>
     */
    public static final Property word = M_MODEL.createProperty("http://example.org/word");
    /**
     * <p></p>
     */
    public static final Resource CommonNoun = M_MODEL.createResource("http://example.org/CommonNoun");
    /**
     * <p>A Entity.</p>
     */
    public static final Resource Entity = M_MODEL.createResource("http://example.org/Entity");
    /**
     * <p>The relation between a phrase and a verb in a tweet, in which the relation
     * is central to the verb.</p>
     */
    public static final Resource Object = M_MODEL.createResource("http://example.org/Object");
    /**
     * <p>Organisation</p>
     */
    public static final Resource Organisation = M_MODEL.createResource("http://example.org/Organisation");
    /**
     * <p>POS.</p>
     */
    public static final Resource POS = M_MODEL.createResource("http://example.org/POS");
    /**
     * <p>Person</p>
     */
    public static final Resource Person = M_MODEL.createResource("http://example.org/Person");
    /**
     * <p>Place</p>
     */
    public static final Resource Place = M_MODEL.createResource("http://example.org/Place");
    /**
     * <p></p>
     */
    public static final Resource ProperNoun = M_MODEL.createResource("http://example.org/ProperNoun");
    /**
     * <p>A subject–verb–object (SVO) sentence structure where the subject comes first,
     * the verb second, and the object third.</p>
     */
    public static final Resource SVO = M_MODEL.createResource("http://example.org/SVO");
    /**
     * <p>The relation between a phrase and a verb in a tweet, that represents the person
     * or thing that performs the action or about which something is stated.</p>
     */
    public static final Resource Subject = M_MODEL.createResource("http://example.org/Subject");
    /**
     * <p>A tweet is a text message limited to 140 characters in length, that is broadcast
     * and readable by anyone who accesses Twitter.</p>
     */
    public static final Resource Tweet = M_MODEL.createResource("http://example.org/Tweet");
    /**
     * <p>An account on the social networking site Twitter</p>
     */
    public static final Resource TwitterAccount = M_MODEL.createResource("http://example.org/TwitterAccount");
    /**
     * <p>A verb signals an action, an occurrence, or a state of being.</p>
     */
    public static final Resource Verb = M_MODEL.createResource("http://example.org/Verb");

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @return namespace as String
     * @see #NS #NS
     */
    public static String getURI() {
        return NS;
    }

}
